---
- hosts: all
  remote_user: pi


  tasks:
    - name: Install GIT
      become: true
      apt:
        name: git
        update_cache: true
        state: present

    - name: Upload public key
      copy:
        src: "{{ git_public_ssh_key_path }}"
        dest: /home/pi/.ssh/id_rsa.pub
        owner: pi
        group: pi
        mode: 0600

    - name: Upload private key
      copy:
        src: "{{ git_private_ssh_key_path }}"
        dest: /home/pi/.ssh/id_rsa
        owner: pi
        group: pi
        mode: 0600


# install Java 8 NOT NEEDED it is already installed in the Raspbian image
# install Clojure using lein

    - name: ensure github.com is a known host
      lineinfile:
        dest: /home/pi/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com"

    - name: Clone RaspPiClojureScreens repo
      git:
        repo: "{{ project_repo }}"
        accept_hostkey: true
        dest: /home/pi/RaspPiClojureScreens


# get a remote desktop working

# install desktop launch shortcuts

