---
- hosts: all
  remote_user: pi


  tasks:
    - name: Install GIT
      become: true
      apt:
        name: git
        update_cache: true
        state: present

    - name: Upload public key
      copy:
        src: "{{ git_public_ssh_key_path }}"
        dest: /home/pi/.ssh/id_rsa.pub
        owner: pi
        group: pi
        mode: 0600

    - name: Upload private key
      copy:
        src: "{{ git_private_ssh_key_path }}"
        dest: /home/pi/.ssh/id_rsa
        owner: pi
        group: pi
        mode: 0600


# install Java 8 NOT NEEDED it is already installed in the Raspbian image
# install Clojure using lein

    - name: ensure github.com is a known host
      lineinfile:
        dest: /home/pi/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com"

    - name: Clone RaspPiClojureScreens repo
      git:
        repo: "{{ project_repo }}"
        accept_hostkey: true
        dest: /home/pi/RaspPiClojureScreens

#Replace RealVNC (Comercial) with tightVNC
    - name: Remove RealVNC Server
      become: true
      apt:
        name: realvnc-vnc-server
        update_cache: true
        state: absent

    - name: Remove RealVNC viewer
      become: true
      apt:
        name: remove realvnc-vnc-viewer
        update_cache: true
        state: absent

    - name: Install tightvncserver
      become: true
      apt:
        name: tightvncserver
        update_cache: true
        state: present

##TODO Set tightVNC password automatically

    - name: Install tightvnc.service file
      become: true
      template:
        src: ./tightvncserver.service
        dest: /etc/systemd/system/tightvncserver.service
        owner: root
        group: root
        mode: 664

    - name: Make sure tightvncserver is running
      become: true
      systemd:
        state: started
        enabled: yes
        daemon_reload: yes
        name: tightvncserver



# TODO install desktop launch shortcuts

